######################################################################
# Automatically generated by qmake (3.0) ?? 7? 4 10:23:45 2013
######################################################################

TEMPLATE = app
TARGET = org.tizen.browser-0.0.1
INCLUDEPATH += . \
               src \
               src/include \
               src/browser-view \
               src/database \
               src/browser-extension \
               src/browser-multi-window \
               src/data-network \
               src/browser-policy-client \
               src/browser-bookmark \
               src/most-visited-sites \
               src/browser-history \
               src/scissorbox \
               src/browser-settings

# Input
HEADERS += src/browser-class.h \
           src/browser-common-view.h \
           src/browser-data-manager.h \
           src/browser-utility.h \
           src/browser-window.h \
           src/browser-bookmark/browser-add-to-bookmark-view.h \
           src/browser-bookmark/browser-bookmark-view.h \
           src/browser-bookmark/browser-new-folder-view.h \
           src/browser-bookmark/browser-select-folder-view.h \
           src/browser-extension/browser-find-word.h \
           src/browser-extension/browser-geolocation.h \
           src/browser-extension/browser-scissorbox-view.h \
           src/browser-history/browser-history-layout.h \
           src/browser-multi-window/browser-multi-window-view.h \
           src/browser-policy-client/browser-policy-decision-maker.h \
           src/browser-settings/browser-settings-class.h \
           src/browser-settings/browser-settings-clear-data-view.h \
           src/browser-settings/browser-settings-edit-homepage-view.h \
           src/browser-settings/browser-settings-main-view.h \
           src/browser-settings/browser-settings-user-agent-view.h \
           src/browser-settings/browser-settings-website-setting.h \
           src/browser-view/browser-context-menu.h \
           src/browser-view/browser-most-visited.h \
           src/browser-view/browser-view.h \
           src/data-network/browser-network-manager.h \
           src/database/browser-bookmark-db.h \
           src/database/browser-geolocation-db.h \
           src/database/browser-history-db.h \
           src/database/browser-user-agent-db.h \
           src/database/most-visited-sites-db.h \
           src/include/browser-config.h \
           src/include/browser-dlog.h \
           src/include/browser-string.h \
           src/most-visited-sites/add-to-most-visited-sites-view.h \
           src/most-visited-sites/most-visited-sites.h \
           src/scissorbox/scissorbox.h
SOURCES += src/browser-class.cpp \
           src/browser-common-view.cpp \
           src/browser-data-manager.cpp \
           src/browser-main.cpp \
           src/browser-utility.cpp \
           src/browser-window.cpp \
           CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           src/browser-bookmark/browser-add-to-bookmark-view.cpp \
           src/browser-bookmark/browser-bookmark-view.cpp \
           src/browser-bookmark/browser-new-folder-view.cpp \
           src/browser-bookmark/browser-select-folder-view.cpp \
           src/browser-extension/browser-find-word.cpp \
           src/browser-extension/browser-geolocation.cpp \
           src/browser-extension/browser-scissorbox-view.cpp \
           src/browser-history/browser-history-layout.cpp \
           src/browser-multi-window/browser-multi-window-view.cpp \
           src/browser-policy-client/browser-policy-decision-maker.cpp \
           src/browser-settings/browser-settings-class.cpp \
           src/browser-settings/browser-settings-clear-data-view.cpp \
           src/browser-settings/browser-settings-edit-homepage-view.cpp \
           src/browser-settings/browser-settings-main-view.cpp \
           src/browser-settings/browser-settings-user-agent-view.cpp \
           src/browser-settings/browser-settings-website-setting.cpp \
           src/browser-view/browser-context-menu.cpp \
           src/browser-view/browser-most-visited.cpp \
           src/browser-view/browser-view.cpp \
           src/data-network/browser-network-manager.cpp \
           src/database/browser-bookmark-db.cpp \
           src/database/browser-geolocation-db.cpp \
           src/database/browser-history-db.cpp \
           src/database/browser-user-agent-db.cpp \
           src/database/most-visited-sites-db.cpp \
           src/most-visited-sites/add-to-most-visited-sites-view.cpp \
           src/most-visited-sites/most-visited-sites.cpp \
           src/scissorbox/scissorbox.cpp
